import {
  BookHeart,
  Calendar,
  ClipboardList,
  Clock,
  FileText,
  FlaskConical,
  GitBranch,
  HandCoins,
  Heart,
  MessageCircle,
  ShieldCheck,
  Sparkles,
  Users,
  ScanSearch,
  MapPin,
  Phone,
} from 'lucide-react';

export const FEATURE_CATALOG_ICONS = {
  cancer_profile: Sparkles,
  doctor_prep: Calendar,
  second_opinion: FileText,
  check_in: ClipboardList,
  timeline: GitBranch,
  trials: FlaskConical,
  goals_of_care: BookHeart,
  insurance: ShieldCheck,
  financial_aid: HandCoins,
  community: MessageCircle,
  empathy_filter: Heart,
  first_72: Clock,
  family: Users,
  complete_the_picture: ScanSearch,
  access_agent: MapPin,
  voice_call_for_me: Phone,
} as const;
