'use client';

import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { FlaskConical } from 'lucide-react';
import { cn } from '@/lib/utils';

export interface CancerProfileSummaryCardProps {
  /** e.g. "Non-Small Cell Lung Cancer" */
  type: string;
  /** e.g. "Stage IIIA" */
  stage?: string;
  /** e.g. ["PD-L1: 60%", "EGFR: Negative"] */
  biomarkers?: string[];
  /** e.g. ["Discuss immunotherapy", "Review clinical trials"] */
  recommendedNextSteps?: string[];
  /** Show primary CTA (e.g. "View full journey") */
  showCta?: boolean;
  /** Compact mode for homepage preview */
  compact?: boolean;
}

export function CancerProfileSummaryCard({
  type,
  stage,
  biomarkers = [],
  recommendedNextSteps = [],
  showCta = true,
  compact = false,
}: CancerProfileSummaryCardProps) {
  return (
    <div
      className={cn(
        'rounded-[var(--radius-xl)] border border-[var(--color-border-subtle)] bg-white shadow-[var(--shadow-md)]',
        compact ? 'p-4' : 'p-6'
      )}
    >
      <p className="inline-flex rounded-full bg-[rgba(95,132,116,0.14)] px-3 py-1 text-[var(--text-xs)] font-semibold uppercase tracking-[var(--tracking-widest)] text-[var(--color-sage-600)]">
        Cancer Profile
      </p>
      <div className={compact ? 'mt-4 space-y-4' : 'mt-6 space-y-5'}>
        <div className="grid gap-4 sm:grid-cols-2">
          <div>
            <p className="text-[var(--text-xs)] font-medium uppercase tracking-wide text-[var(--color-text-muted)]">
              Type
            </p>
            <p
              className={cn(
                'mt-1 font-display font-semibold text-[var(--color-primary-900)]',
                compact ? 'text-base' : 'text-lg'
              )}
            >
              {type}
            </p>
          </div>
          {stage && (
            <div>
              <p className="text-[var(--text-xs)] font-medium uppercase tracking-wide text-[var(--color-text-muted)]">
                Stage
              </p>
              <p
                className={cn(
                  'mt-1 font-display font-semibold text-[var(--color-primary-900)]',
                  compact ? 'text-base' : 'text-lg'
                )}
              >
                {stage}
              </p>
            </div>
          )}
        </div>
        {biomarkers.length > 0 && (
          <div>
            <p className="flex items-center gap-1.5 text-[var(--text-xs)] font-medium uppercase tracking-wide text-[var(--color-text-muted)]">
              <FlaskConical className="h-3.5 w-3.5 text-[var(--color-sage-500)]" aria-hidden />
              Key Biomarkers
            </p>
            <div className="mt-2 flex flex-wrap gap-2">
              {biomarkers.map((b, i) => (
                <span
                  key={b}
                  className={cn(
                    'rounded-full px-3 py-1 text-[var(--text-xs)] font-semibold',
                    i % 2 === 0
                      ? 'bg-[rgba(95,132,116,0.16)] text-[var(--color-sage-600)]'
                      : 'bg-[rgba(58,97,134,0.12)] text-[var(--color-primary-700)]'
                  )}
                >
                  {b}
                </span>
              ))}
            </div>
          </div>
        )}
        {recommendedNextSteps.length > 0 && (
          <div>
            <p className="text-[var(--text-xs)] font-medium uppercase tracking-wide text-[var(--color-text-muted)]">
              Recommended Next Steps
            </p>
            <ul className="mt-3 space-y-2.5">
              {recommendedNextSteps.map((step, i) => (
                <li key={i} className="flex gap-3 text-sm leading-snug text-[var(--color-text-secondary)]">
                  <span
                    className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[var(--color-accent-400)] text-xs font-bold text-[var(--color-primary-900)]"
                    aria-hidden
                  >
                    {i + 1}
                  </span>
                  <span className="pt-0.5">{step}</span>
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>
      <p className="mt-4 border-t border-[var(--color-border-subtle)] pt-3 text-center text-[var(--text-xs)] text-[var(--color-text-muted)]">
        Generated by OncoKind
      </p>
      {showCta && !compact && (
        <Button asChild size="sm" className="mt-4 w-full sm:w-auto">
          <Link href="/journey">View full journey</Link>
        </Button>
      )}
    </div>
  );
}
