DROP POLICY IF EXISTS program_versions_read ON public.program_versions;
DROP POLICY IF EXISTS programs_read ON public.programs;
DROP POLICY IF EXISTS agent_audit_read ON public.agent_audit_log;
DROP POLICY IF EXISTS agent_audit_insert ON public.agent_audit_log;
DROP POLICY IF EXISTS voice_call_events_via_call ON public.voice_call_events;
DROP POLICY IF EXISTS application_events_via_app ON public.application_events;
DROP POLICY IF EXISTS run_events_via_run ON public.run_events;
DROP POLICY IF EXISTS outcome_feedback_self ON public.outcome_feedback;
DROP POLICY IF EXISTS rule_evaluations_self ON public.rule_evaluations;
DROP POLICY IF EXISTS extraction_corrections_self ON public.extraction_corrections;
DROP POLICY IF EXISTS agent_documents_self ON public.agent_documents;
DROP POLICY IF EXISTS notification_prefs_self ON public.notification_prefs;
DROP POLICY IF EXISTS agent_consents_self ON public.agent_consents;
DROP POLICY IF EXISTS voice_calls_self ON public.voice_calls;
DROP POLICY IF EXISTS applications_self ON public.applications;
DROP POLICY IF EXISTS access_intakes_self ON public.access_intakes;
DROP POLICY IF EXISTS question_tracker_self ON public.question_tracker;
DROP POLICY IF EXISTS extractions_self ON public.extractions;
DROP POLICY IF EXISTS agent_runs_self ON public.agent_runs;

DROP TABLE IF EXISTS public.agent_audit_log;
DROP TABLE IF EXISTS public.notification_prefs;
DROP TABLE IF EXISTS public.agent_consents;
DROP TABLE IF EXISTS public.voice_call_events;
DROP TABLE IF EXISTS public.voice_calls;
DROP TABLE IF EXISTS public.application_events;
DROP TABLE IF EXISTS public.applications;
DROP TABLE IF EXISTS public.program_verifications;
DROP TABLE IF EXISTS public.program_versions;
DROP TABLE IF EXISTS public.programs;
DROP TABLE IF EXISTS public.access_intakes;
DROP TABLE IF EXISTS public.outcome_feedback;
DROP TABLE IF EXISTS public.question_tracker;
DROP TABLE IF EXISTS public.rule_evaluations;
DROP TABLE IF EXISTS public.rule_versions;
DROP TABLE IF EXISTS public.extraction_corrections;
DROP TABLE IF EXISTS public.extractions;
DROP TABLE IF EXISTS public.agent_documents;
DROP TABLE IF EXISTS public.run_events;
DROP TABLE IF EXISTS public.agent_runs;
